/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;
import model.PersonHistory;

/**
 *
 * @author libby
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    PersonHistory history;
    
    public CreateJPanel(PersonHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lalTitle = new javax.swing.JLabel();
        lalName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lalPersonalInfo1 = new javax.swing.JLabel();
        lalAddress = new javax.swing.JLabel();
        lalBirth = new javax.swing.JLabel();
        lalTelePhone = new javax.swing.JLabel();
        lalFaxPhone = new javax.swing.JLabel();
        lalEmail = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        txtTelePhone = new javax.swing.JTextField();
        txtFaxPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lalOtherInfo = new javax.swing.JLabel();
        lalSsn = new javax.swing.JLabel();
        lalMedicalNum = new javax.swing.JLabel();
        lalHealthPlanNum = new javax.swing.JLabel();
        lalBankNum = new javax.swing.JLabel();
        lalLicenseNum = new javax.swing.JLabel();
        lalVehicleNum = new javax.swing.JLabel();
        lalDeviceNum = new javax.swing.JLabel();
        lalLinkedin = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        txtMedicalNum = new javax.swing.JTextField();
        txtBankNum = new javax.swing.JTextField();
        txtHealthNum = new javax.swing.JTextField();
        txtLicenseNum = new javax.swing.JTextField();
        txtVehicleNum = new javax.swing.JTextField();
        txtDeviceNum = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lalPhoto = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        lalTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lalTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalTitle.setText("Create Profile");

        lalName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalName.setText("Name:");

        lalPersonalInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lalPersonalInfo1.setText("Personal Info");

        lalAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalAddress.setText("Address:");

        lalBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalBirth.setText("Birth:");

        lalTelePhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalTelePhone.setText("Telephone:");

        lalFaxPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalFaxPhone.setText("Fax:");

        lalEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalEmail.setText("Email:");

        lalOtherInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lalOtherInfo.setText("Other Info");

        lalSsn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalSsn.setText("SSN:");

        lalMedicalNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalMedicalNum.setText("Medical Record Num:");

        lalHealthPlanNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalHealthPlanNum.setText("Health Plan Beneficiary Num:");

        lalBankNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalBankNum.setText("Bank Account:");

        lalLicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalLicenseNum.setText("Certificate / License Num:");

        lalVehicleNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalVehicleNum.setText("Vehicle Identifiers & Serial Num:");

        lalDeviceNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalDeviceNum.setText("Device Identifiers & Serial Num:");

        lalLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalLinkedin.setText("LinkedIn:");

        txtHealthNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthNumActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lalPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpload.setText("Upload");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lalTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lalPersonalInfo1)
                                            .addComponent(lalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lalAddress)
                                            .addComponent(lalName)
                                            .addComponent(lalBirth)
                                            .addComponent(lalFaxPhone)
                                            .addComponent(lalEmail)
                                            .addComponent(lalTelePhone)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(btnUpload)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(txtTelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFaxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lalVehicleNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                    .addComponent(txtVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lalOtherInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lalHealthPlanNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lalDeviceNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lalSsn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lalMedicalNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lalBankNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lalLicenseNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lalLinkedin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(btnSave)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lalTitle)
                .addGap(18, 18, 18)
                .addComponent(lalPersonalInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lalOtherInfo)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalName))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalBirth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalTelePhone))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalFaxPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalEmail))
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lalSsn)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lalMedicalNum)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalHealthPlanNum)
                    .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalBankNum)
                    .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalLicenseNum)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalVehicleNum)
                    .addComponent(txtVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalDeviceNum)
                    .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lalLinkedin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Person p = history.newPerson();
        
        p.setName(txtName.getText());
        p.setBirth(txtBirth.getText());
        p.setAddress(txtAddress.getText());
        p.setTelePhone(txtTelePhone.getText());
        p.setFaxPhone(txtFaxPhone.getText());
        p.setEmail(txtEmail.getText());
        p.setSocialSecurityNum(txtSsn.getText());
        p.setMedicalRecordNum(txtMedicalNum.getText());
        p.setHealthPlanNum(txtHealthNum.getText());
        p.setBankAccountNum(txtBankNum.getText());
        p.setLicenseNum(txtLicenseNum.getText());
        p.setVehicleIdentifiers(txtVehicleNum.getText());
        p.setDeviceIdentifiers(txtDeviceNum.getText());
        p.setLinkedIn(txtLinkedin.getText());
        
        JOptionPane.showMessageDialog(this, "New profile saved");
        clearTextField();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtHealthNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthNumActionPerformed

    public void clearTextField(){
        txtName.setText("");
        txtBirth.setText("");
        txtAddress.setText("");
        txtTelePhone.setText("");
        txtFaxPhone.setText("");
        txtEmail.setText("");
        txtSsn.setText("");
        txtMedicalNum.setText("");
        txtHealthNum.setText("");
        txtBankNum.setText("");
        txtLicenseNum.setText("");
        txtVehicleNum.setText("");
        txtDeviceNum.setText("");
        txtLinkedin.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lalAddress;
    private javax.swing.JLabel lalBankNum;
    private javax.swing.JLabel lalBirth;
    private javax.swing.JLabel lalDeviceNum;
    private javax.swing.JLabel lalEmail;
    private javax.swing.JLabel lalFaxPhone;
    private javax.swing.JLabel lalHealthPlanNum;
    private javax.swing.JLabel lalLicenseNum;
    private javax.swing.JLabel lalLinkedin;
    private javax.swing.JLabel lalMedicalNum;
    private javax.swing.JLabel lalName;
    private javax.swing.JLabel lalOtherInfo;
    private javax.swing.JLabel lalPersonalInfo1;
    private javax.swing.JLabel lalPhoto;
    private javax.swing.JLabel lalSsn;
    private javax.swing.JLabel lalTelePhone;
    private javax.swing.JLabel lalTitle;
    private javax.swing.JLabel lalVehicleNum;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankNum;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtDeviceNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxPhone;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTelePhone;
    private javax.swing.JTextField txtVehicleNum;
    // End of variables declaration//GEN-END:variables
}
