/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonHistory;

/**
 *
 * @author libby
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    PersonHistory history;
    
    public ViewJPanel(PersonHistory history) {
        initComponents();
        this.history = history;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lalTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        lalTelePhone = new javax.swing.JLabel();
        lalFaxPhone = new javax.swing.JLabel();
        lalEmail = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        txtTelePhone = new javax.swing.JTextField();
        txtFaxPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lalName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lalAddress = new javax.swing.JLabel();
        lalBirth = new javax.swing.JLabel();
        txtHealthNum = new javax.swing.JTextField();
        lalSsn = new javax.swing.JLabel();
        lalMedicalNum = new javax.swing.JLabel();
        lalHealthPlanNum = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        txtMedicalNum = new javax.swing.JTextField();
        txtBankNum = new javax.swing.JTextField();
        txtLicenseNum = new javax.swing.JTextField();
        txtVehicleNum = new javax.swing.JTextField();
        txtDeviceNum = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        lalBankNum = new javax.swing.JLabel();
        lalLicenseNum = new javax.swing.JLabel();
        lalVehicleNum = new javax.swing.JLabel();
        lalDeviceNum = new javax.swing.JLabel();
        lalLinkedin = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lalPhoto = new javax.swing.JLabel();

        lalTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lalTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalTitle.setText("View Profile");

        viewTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewTable.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Birth", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        lalTelePhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalTelePhone.setText("Telephone:");

        lalFaxPhone.setText("Fax:");

        lalEmail.setText("Email:");

        lalName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalName.setText("Name:");

        lalAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalAddress.setText("Address:");

        lalBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalBirth.setText("Birth:");

        lalSsn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalSsn.setText("SSN:");

        lalMedicalNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalMedicalNum.setText("Medical Record Num:");

        lalHealthPlanNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalHealthPlanNum.setText("Health Plan Beneficiary Num:");

        lalBankNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalBankNum.setText("Bank Account:");

        lalLicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalLicenseNum.setText("Certificate / License Num:");

        lalVehicleNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalVehicleNum.setText("Vehicle Identifiers & Serial Num:");

        lalDeviceNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalDeviceNum.setText("Device Identifiers & Serial Num:");

        lalLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lalLinkedin.setText("LinkedIn:");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lalPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lalPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lalPhoto.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lalTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lalName)
                                            .addComponent(lalBirth))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lalEmail)
                                                    .addComponent(lalFaxPhone)
                                                    .addComponent(lalTelePhone)
                                                    .addComponent(lalSsn)
                                                    .addComponent(lalAddress))
                                                .addGap(81, 81, 81))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lalMedicalNum)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelePhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFaxPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSsn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(btnView)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lalBankNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lalHealthPlanNum)
                                .addGap(27, 27, 27)
                                .addComponent(txtHealthNum))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lalVehicleNum)
                                    .addComponent(lalDeviceNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVehicleNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeviceNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lalLicenseNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lalLinkedin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnView))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalSsn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalTelePhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalFaxPhone)))
                    .addComponent(lalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalEmail)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalMedicalNum)
                    .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalBirth))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalHealthPlanNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalBankNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalLicenseNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalVehicleNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalDeviceNum)
                    .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lalLinkedin))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = viewTable.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a profile to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) viewTable.getModel();
        Person p = (Person) model.getValueAt(selectedRowIndex, 0);
        history.deletePerson(p);
        
        JOptionPane.showMessageDialog(this, "Selected profile deleted");
        
        populateTable();
        clearTextField();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = viewTable.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a profile to view");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) viewTable.getModel();
        Person p = (Person) model.getValueAt(selectedRowIndex, 0);
        
        txtName.setText(p.getName());
        txtBirth.setText(p.getBirth());
        txtAddress.setText(p.getAddress());
        txtTelePhone.setText(p.getTelePhone());
        txtFaxPhone.setText(p.getFaxPhone());
        txtEmail.setText(p.getEmail());
        txtSsn.setText(p.getSocialSecurityNum());
        txtMedicalNum.setText(p.getMedicalRecordNum());
        txtHealthNum.setText(p.getHealthPlanNum());
        txtBankNum.setText(p.getBankAccountNum());
        txtLicenseNum.setText(p.getLicenseNum());
        txtVehicleNum.setText(p.getVehicleIdentifiers());
        txtDeviceNum.setText(p.getDeviceIdentifiers());
        txtLinkedin.setText(p.getLinkedIn());
        
        lalPhoto.setIcon(p.getPhoto());
    }//GEN-LAST:event_btnViewActionPerformed

    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) viewTable.getModel();
        model.setRowCount(0);
        
        for(Person p : history.getHistory()){
            
            Object[] row = new Object[3];
            row[0] = p;
            row[1] = p.getBirth();
            row[2] = p.getTelePhone();
            model.addRow(row);
        }
        
    }
    
    public void clearTextField(){
        txtName.setText("");
        txtBirth.setText("");
        txtAddress.setText("");
        txtTelePhone.setText("");
        txtFaxPhone.setText("");
        txtEmail.setText("");
        txtSsn.setText("");
        txtMedicalNum.setText("");
        txtHealthNum.setText("");
        txtBankNum.setText("");
        txtLicenseNum.setText("");
        txtVehicleNum.setText("");
        txtDeviceNum.setText("");
        txtLinkedin.setText("");
        lalPhoto.setIcon(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lalAddress;
    private javax.swing.JLabel lalBankNum;
    private javax.swing.JLabel lalBirth;
    private javax.swing.JLabel lalDeviceNum;
    private javax.swing.JLabel lalEmail;
    private javax.swing.JLabel lalFaxPhone;
    private javax.swing.JLabel lalHealthPlanNum;
    private javax.swing.JLabel lalLicenseNum;
    private javax.swing.JLabel lalLinkedin;
    private javax.swing.JLabel lalMedicalNum;
    private javax.swing.JLabel lalName;
    private javax.swing.JLabel lalPhoto;
    private javax.swing.JLabel lalSsn;
    private javax.swing.JLabel lalTelePhone;
    private javax.swing.JLabel lalTitle;
    private javax.swing.JLabel lalVehicleNum;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankNum;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtDeviceNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxPhone;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTelePhone;
    private javax.swing.JTextField txtVehicleNum;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
