/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Create;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Bank;
import model.Person;
import model.PersonHistory;

/**
 *
 * @author libby
 */
public class CreatePanel5 extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel5
     */
    
    PersonHistory history;
    JPanel userProcessContainer;
    Person person;
    
    public CreatePanel5(PersonHistory history, JPanel userProcessContainer, Person person) {
        initComponents();
        this.history = history;
        this.userProcessContainer = userProcessContainer;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        selectAccountType = new javax.swing.JComboBox<>();
        lblAccountType = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        lblRouting = new javax.swing.JLabel();
        txtRouting = new javax.swing.JTextField();
        lblAccount = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle.setText("Create Personal Profile: Step 5 of 6");

        lblTitle2.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle2.setText("Bank Account Information");

        selectAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Checking" }));
        selectAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAccountTypeActionPerformed(evt);
            }
        });

        lblAccountType.setText("Account type:");

        lblBankName.setText("Bank Name:");

        lblRouting.setText("Routing #:");

        lblAccount.setText("Account #:");

        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Bank Name", "Routing Number", "Account Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAccount);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle2)
                            .addComponent(lblTitle)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAccountType)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRouting)
                                        .addGap(40, 40, 40)
                                        .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAccount)
                                    .addComponent(lblBankName))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAccount)
                                    .addComponent(txtBankName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblTitle2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType)
                    .addComponent(selectAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRouting)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccount))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAccountTypeActionPerformed

    }//GEN-LAST:event_selectAccountTypeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        person.getBank().clear();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if(tableAccount.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Please enter at least one account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            CreatePanel6 cp = new CreatePanel6(history, userProcessContainer,person);
            userProcessContainer.add("CreatePanel6",cp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        DefaultTableModel model = (DefaultTableModel) tableAccount.getModel();
        int selectedEmailIndex = tableAccount.getSelectedRow();

        if(selectedEmailIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select an account to delete");
        } else {
            Bank b = (Bank) tableAccount.getValueAt(selectedEmailIndex, 1);
            person.deleteBank(b);
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if(txtBankName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please complete all the blanks", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(txtRouting.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please complete all the blanks", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(txtAccount.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please complete all the blanks", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String accountType = (String) selectAccountType.getSelectedItem();
        person.addBank(txtBankName.getText(), txtRouting.getText(), txtAccount.getText(), accountType);
        
        populateTable();
        
        txtBankName.setText("");
        txtRouting.setText("");
        txtAccount.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) tableAccount.getModel();
        model.setRowCount(0);
        
        for(Bank b : person.getBank()){
            Object[] row = new Object[4];
            row[0] = b.getType();
            row[1] = b;
            row[2] = b.getRouting();
            row[3] = b.getAccount();
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblRouting;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JComboBox<String> selectAccountType;
    private javax.swing.JTable tableAccount;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRouting;
    // End of variables declaration//GEN-END:variables
}
