/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.View;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Address;
import model.Bank;
import model.Device;
import model.Email;
import model.Person;
import model.Vehicle;

/**
 *
 * @author libby
 */
public class ViewPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel2
     */
    
    Person person;
    JPanel userProcessContainer;
    
    public ViewPanel2(Person person, JPanel userProcessContainer) {
        initComponents();
        this.person = person;
        this.userProcessContainer = userProcessContainer;
        populateProfile();
    }
    
    private void populateTableAddress(){
        
        DefaultTableModel model = (DefaultTableModel) tableAddress.getModel();
        model.setRowCount(0);
        
        for(Address a : person.getAddress()){
            Object[] row = new Object[2];
            row[0] = a.getType();
            row[1] = a.printAddress();

            model.addRow(row);
        }
    }
    
    private void populateTableEmail(){
        
        DefaultTableModel model = (DefaultTableModel) tableAddress1.getModel();
        model.setRowCount(0);
        
        for(Email e : person.getEmail()){
            Object[] row = new Object[2];
            row[0] = e.getType();
            row[1] = e.getEmail();

            model.addRow(row);
        }
    }
    
    private void populateDeviceVehicleHealth(){
        
        Device d = person.getDevice();
        txtDeviceType.setText(d.getType());
        txtDeviceModel.setText(d.getModel());
        txtIMEI.setText(d.getIMEI());
        
        Vehicle v = person.getVehicle();
        txtVehicleType.setText(v.getType());
        txtVehicleModel.setText(v.getModel());
        txtPlate.setText(v.getPlate());
        
        txtMedicalRecordNumber.setText(person.getMedicalRecordNum());
        txtHealthPlanNumber.setText(person.getHealthPlanNum());
    }
    
    private void populateTableAccount(){
        
        DefaultTableModel model = (DefaultTableModel) tableAccount.getModel();
        model.setRowCount(0);
        
        for(Bank b : person.getBank()){
            Object[] row = new Object[4];
            row[0] = b.getType();
            row[1] = b.getBankName();
            row[2] = b.getRouting();
            row[3] = b.getAccount();

            model.addRow(row);
        }
    }
    
    private void populateProfile(){
        
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtBirth.setText(person.getBirth());
        txtSSN.setText(person.getSSN());
        lalPhoto.setIcon(person.getPhoto());
        
        populateTableAddress();
        populateDeviceVehicleHealth();
        populateTableAccount();
        populateTableEmail();
        txtPhoneNumber.setText(person.getTelePhone());
        txtFaxNumber.setText(person.getFaxPhone());
        
        txtCertificationNumber.setText(person.getCertification().getNumber());
        txtCertificationDate.setText(person.getCertification().getDate());
        txtLinkedIn.setText(person.getLinkedIn());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPersonalInfo = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtBirth = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lalPhoto = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jPanelAddresses = new javax.swing.JPanel();
        lblTitle4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAddress = new javax.swing.JTable();
        jPanelPhoneEmail = new javax.swing.JPanel();
        lblTitle6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAddress1 = new javax.swing.JTable();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFaxNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        jPanelDeviceVehicleHealthInfo = new javax.swing.JPanel();
        txtHealthPlanNumber = new javax.swing.JTextField();
        lblDeviceModel = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtDeviceModel = new javax.swing.JTextField();
        txtDeviceType = new javax.swing.JTextField();
        lblIMEI = new javax.swing.JLabel();
        txtVehicleType = new javax.swing.JTextField();
        txtIMEI = new javax.swing.JTextField();
        lblVehicleModel = new javax.swing.JLabel();
        lblVehicleType = new javax.swing.JLabel();
        txtVehicleModel = new javax.swing.JTextField();
        lblTitle5 = new javax.swing.JLabel();
        lblPlate = new javax.swing.JLabel();
        txtPlate = new javax.swing.JTextField();
        lblHealthPlanNumber = new javax.swing.JLabel();
        lblTitle7 = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblDeviceType = new javax.swing.JLabel();
        jPanelBankAccounts = new javax.swing.JPanel();
        lblTitle8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();
        jPanelProfessionalInfo = new javax.swing.JPanel();
        txtCertificationNumber = new javax.swing.JTextField();
        txtCertificationDate = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        lblTitle9 = new javax.swing.JLabel();
        lblCertificationNumber = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblCertificationDate = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle.setText("View Personal Profile: Part 1 of 6");

        txtBirth.setEditable(false);

        txtSSN.setEditable(false);

        lalPhoto.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lalPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalPhoto.setText("No image to display");
        lalPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lalPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lalPhoto.setPreferredSize(new java.awt.Dimension(200, 200));

        lblTitle2.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle2.setText("Personal Information");

        lblTitle3.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle3.setText("Profile Image");

        lblFirstName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblFirstName.setText("First Name:");

        lblLastName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        lblBirth.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirth.setText("Date of Birth:");

        lblSSN.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblSSN.setText("SSN:");

        txtFirstName.setEditable(false);

        txtLastName.setEditable(false);
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPersonalInfoLayout = new javax.swing.GroupLayout(jPanelPersonalInfo);
        jPanelPersonalInfo.setLayout(jPanelPersonalInfoLayout);
        jPanelPersonalInfoLayout.setHorizontalGroup(
            jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblTitle))
                    .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle2)
                            .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSSN)
                                    .addComponent(lblBirth))
                                .addGap(26, 26, 26)
                                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle3)
                            .addComponent(lalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelPersonalInfoLayout.setVerticalGroup(
            jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(lblTitle3))
                .addGap(18, 18, 18)
                .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPersonalInfoLayout.createSequentialGroup()
                        .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName))
                        .addGap(17, 17, 17)
                        .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirth))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN)))
                    .addComponent(lalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Info", jPanelPersonalInfo);

        lblTitle4.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle4.setText("Contact Information");

        tableAddress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAddress);

        javax.swing.GroupLayout jPanelAddressesLayout = new javax.swing.GroupLayout(jPanelAddresses);
        jPanelAddresses.setLayout(jPanelAddressesLayout);
        jPanelAddressesLayout.setHorizontalGroup(
            jPanelAddressesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddressesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanelAddressesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddressesLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lblTitle4)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );
        jPanelAddressesLayout.setVerticalGroup(
            jPanelAddressesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddressesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanelAddressesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddressesLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTitle4)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Addresses", jPanelAddresses);

        lblTitle6.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle6.setText("Contact Information");

        tableAddress1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableAddress1);

        txtPhoneNumber.setEditable(false);

        txtFaxNumber.setEditable(false);

        lblPhoneNumber.setText("Phone Number:");

        lblFaxNumber.setText("Fax Number:");

        javax.swing.GroupLayout jPanelPhoneEmailLayout = new javax.swing.GroupLayout(jPanelPhoneEmail);
        jPanelPhoneEmail.setLayout(jPanelPhoneEmailLayout);
        jPanelPhoneEmailLayout.setHorizontalGroup(
            jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhoneEmailLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPhoneEmailLayout.createSequentialGroup()
                        .addGroup(jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFaxNumber)
                            .addComponent(lblPhoneNumber))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle6))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelPhoneEmailLayout.setVerticalGroup(
            jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhoneEmailLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle6)
                .addGap(9, 9, 9)
                .addGroup(jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPhoneEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNumber))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phone & Email", jPanelPhoneEmail);

        txtHealthPlanNumber.setEditable(false);

        lblDeviceModel.setText("Model:");

        txtMedicalRecordNumber.setEditable(false);

        txtDeviceModel.setEditable(false);

        txtDeviceType.setEditable(false);

        lblIMEI.setText("IMEI:");

        txtVehicleType.setEditable(false);

        txtIMEI.setEditable(false);

        lblVehicleModel.setText("Model:");

        lblVehicleType.setText("Vehicle Type:");

        txtVehicleModel.setEditable(false);

        lblTitle5.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle5.setText("Health Information");

        lblPlate.setText("Plate:");

        txtPlate.setEditable(false);

        lblHealthPlanNumber.setText("Health Plan Beneficiary Number:");

        lblTitle7.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle7.setText("Device & Vehicle Information");

        lblMedicalRecordNumber.setText("Medical Record Number:");

        lblDeviceType.setText("Device Type:");

        javax.swing.GroupLayout jPanelDeviceVehicleHealthInfoLayout = new javax.swing.GroupLayout(jPanelDeviceVehicleHealthInfo);
        jPanelDeviceVehicleHealthInfo.setLayout(jPanelDeviceVehicleHealthInfoLayout);
        jPanelDeviceVehicleHealthInfoLayout.setHorizontalGroup(
            jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMedicalRecordNumber)
                                .addComponent(lblHealthPlanNumber))
                            .addGap(27, 27, 27)
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMedicalRecordNumber)
                                .addComponent(txtHealthPlanNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)))
                        .addComponent(lblTitle5)
                        .addComponent(lblTitle7)
                        .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDeviceType)
                                .addComponent(lblVehicleType))
                            .addGap(8, 8, 8)
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(txtVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                                    .addComponent(lblDeviceModel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDeviceModel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                                    .addComponent(lblVehicleModel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPlate)
                                .addComponent(lblIMEI))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        jPanelDeviceVehicleHealthInfoLayout.setVerticalGroup(
            jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDeviceVehicleHealthInfoLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lblTitle7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeviceType)
                        .addComponent(lblDeviceModel)
                        .addComponent(txtDeviceModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIMEI)
                        .addComponent(txtIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVehicleType)
                        .addComponent(txtVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVehicleModel)
                        .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPlate)
                        .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(lblTitle5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMedicalRecordNumber))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelDeviceVehicleHealthInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHealthPlanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHealthPlanNumber))
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Device & Vehicle & Health Info", jPanelDeviceVehicleHealthInfo);

        lblTitle8.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle8.setText("Bank Account Information");

        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Bank Name", "Routing Number", "Account Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableAccount);

        javax.swing.GroupLayout jPanelBankAccountsLayout = new javax.swing.GroupLayout(jPanelBankAccounts);
        jPanelBankAccounts.setLayout(jPanelBankAccountsLayout);
        jPanelBankAccountsLayout.setHorizontalGroup(
            jPanelBankAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanelBankAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBankAccountsLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanelBankAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        jPanelBankAccountsLayout.setVerticalGroup(
            jPanelBankAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanelBankAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBankAccountsLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblTitle8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Bank Accounts", jPanelBankAccounts);

        txtCertificationNumber.setEditable(false);

        txtCertificationDate.setEditable(false);

        txtLinkedIn.setEditable(false);

        lblTitle9.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTitle9.setText("Professional Certification & Social Network Information");

        lblCertificationNumber.setText("Certification Number:");

        lblLinkedIn.setText("LinkedIn:");

        lblCertificationDate.setText("Certification Date:");

        javax.swing.GroupLayout jPanelProfessionalInfoLayout = new javax.swing.GroupLayout(jPanelProfessionalInfo);
        jPanelProfessionalInfo.setLayout(jPanelProfessionalInfoLayout);
        jPanelProfessionalInfoLayout.setHorizontalGroup(
            jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProfessionalInfoLayout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle9)
                        .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelProfessionalInfoLayout.createSequentialGroup()
                                .addComponent(lblLinkedIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProfessionalInfoLayout.createSequentialGroup()
                                .addComponent(lblCertificationDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCertificationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProfessionalInfoLayout.createSequentialGroup()
                                .addComponent(lblCertificationNumber)
                                .addGap(35, 35, 35)
                                .addComponent(txtCertificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        jPanelProfessionalInfoLayout.setVerticalGroup(
            jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProfessionalInfoLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(lblTitle9)
                    .addGap(23, 23, 23)
                    .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCertificationNumber)
                        .addComponent(txtCertificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCertificationDate)
                        .addComponent(txtCertificationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(jPanelProfessionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLinkedIn)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Professional Info", jPanelProfessionalInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed

    }//GEN-LAST:event_txtLastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAddresses;
    private javax.swing.JPanel jPanelBankAccounts;
    private javax.swing.JPanel jPanelDeviceVehicleHealthInfo;
    private javax.swing.JPanel jPanelPersonalInfo;
    private javax.swing.JPanel jPanelPhoneEmail;
    private javax.swing.JPanel jPanelProfessionalInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lalPhoto;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblCertificationDate;
    private javax.swing.JLabel lblCertificationNumber;
    private javax.swing.JLabel lblDeviceModel;
    private javax.swing.JLabel lblDeviceType;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHealthPlanNumber;
    private javax.swing.JLabel lblIMEI;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPlate;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JLabel lblVehicleModel;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JTable tableAccount;
    private javax.swing.JTable tableAddress;
    private javax.swing.JTable tableAddress1;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtCertificationDate;
    private javax.swing.JTextField txtCertificationNumber;
    private javax.swing.JTextField txtDeviceModel;
    private javax.swing.JTextField txtDeviceType;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHealthPlanNumber;
    private javax.swing.JTextField txtIMEI;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtVehicleModel;
    private javax.swing.JTextField txtVehicleType;
    // End of variables declaration//GEN-END:variables
}
